title: bluemomo
description: >  # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bluemomo112.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: 蓝精灵
tagline: 课程设计师.喵族
about-description: 啦啦啦啦，总而言之一句话，你知道我非常厉害就对了！ # Add Discription
pic: lan.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: 164213221@qq.com # Add your Email address
phone: xxx xxx xxx # Add your Phone number
website: https://bluemomo112.github.io/coolCV # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: bluemomo112 # Add your Github handle
twitter: 'lalala' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: 厉害了word哥 # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
